import turtle
turtle. circle (40)
turtle. penup ()
turtle. forward (100)
turtle. pendown()
turtle. circle (40)
turtle. penup ()
turtle. forward (100)
turtle. pendown()
turtle. circle (40)
turtle.left(-90)
turtle. penup()
turtle. forward (40)
turtle.left(-90)
turtle.forward(50)
turtle.pendown()
turtle.left(180)
turtle.circle(40)
turtle.left(180)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(180)
turtle. circle(40)
